installdir = $(pkglibdir)/python/Plugins/Extensions/TNAPHelp

install_PYTHON = __init__.py plugin.py

enigma2helpdir = $(datadir)/enigma2/help
dist_enigma2help_DATA = \
	help/pip-guide.txt \
	help/debug-capture.txt \
	help/storage-trim.txt \
	help/device-manager.txt \
	help/ssh-telnet-access.txt \
	help/multiboot-slots.txt
